version: "3.7"

services:

  traefik:
    container_name: traefik_v1
    image: traefik:1.7
    restart: always
    networks:
      - gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    ports:
      - 80:80
      - 443:443
      - 8080:8080

networks:
  gateway:
